# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 3.1'

gem 'dotenv-rails', '~> 2.7'

gem 'aasm', '~> 5.2'
gem 'activerecord-nulldb-adapter', '~> 0.8'
gem 'addressable', '~> 2.8'
gem 'after_commit_everywhere', '~> 1.2'
gem 'ancestry', '~> 4.1'
gem 'authtrail', '~> 0.4.2'
gem 'awesome_print', '~> 1.9'
gem 'bcrypt', '~> 3.1'
gem 'better_html', '~> 1.0'
gem 'bootsnap', require: false
gem 'composite_primary_keys', '~> 14.0'
gem 'devise', '~> 4.8'
gem 'discard', '~> 1.2'
gem 'down', '~> 5.3'
gem 'flamegraph', '~> 0.9.5'
gem 'get_process_mem', '~> 0.2.7'
gem 'hiredis', '~> 0.6.3'
gem 'http', '~> 5.0'
gem 'importmap-rails', '~> 1.1'
gem 'jbuilder', '~> 2.11'
gem 'jwt', '~> 2.3'
gem 'kaminari', '~> 1.2'
gem 'kredis', '~> 1.2'
gem 'local_time', '~> 2.1'
gem 'logidze', github: 'baygeldin/logidze', branch: 'fix/support-json-columns'
gem 'memory_profiler', '~> 1.0'
gem 'oauth2', '~> 1.4'
gem 'oj', '~> 3.13'
gem 'omniauth-oauth2', '~> 1.7'
gem 'omniauth-rails_csrf_protection', '~> 1.0'
gem 'paper_trail', '~> 12.3'
gem 'parallel', '~> 1.22'
gem 'pg', '~> 1.3'
gem 'pg_search', '~> 2.3'
gem 'pretender', '~> 0.4.0'
gem 'pry-rails', '~> 0.3.9'
gem 'puma', '~> 5.0'
gem 'pundit', '~> 2.2'
gem 'rack-mini-profiler'
gem 'rails', '~> 7.0.3'
gem 'redis', '~> 4.0'
gem 'repost', '~> 0.3.8'
gem 'retriable', '~> 3.1'
gem 'sidekiq', '~> 6.4'
gem 'sidekiq-batch', '~> 0.1.8'
gem 'sidekiq-scheduler', '~> 4.0'
gem 'sidekiq-throttled', '~> 0.15.0'
gem 'sidekiq-unique-jobs', '~> 7.1'
gem 'sprockets-rails', '~> 3.4'
gem 'stackprof', '~> 0.2.19'
gem 'stimulus-rails', '~> 1.0'
gem 'tailwindcss-rails', '~> 2.0'
gem 'tty-command', '~> 0.10.1'
gem 'tty-progressbar', '~> 0.18.2'
gem 'turbo-rails', '~> 1.1'
gem 'typhoeus', '~> 1.4'
gem 'view_component', '~> 2.51'

group :development, :test do
  gem 'debug', '~> 1.5'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 2.21'
  gem 'i18n-tasks', '~> 1.0'
  gem 'lookbook', '~> 0.8'
  gem 'rspec-rails', '~> 5.1'
end

group :development do
  gem 'annotate', '~> 3.2'
  gem 'benchmark-ips', '~> 2.10'
  gem 'brakeman', '~> 5.2'
  gem 'bundler-audit', '~> 0.9.1'
  gem 'bundler-leak', '~> 0.3.0'
  gem 'derailed_benchmarks', '~> 2.1'
  gem 'erb_lint', '~> 0.1.1'
  gem 'kramdown-parser-gfm', '~> 1.1'
  gem 'rouge', '~> 3.28'
  gem 'rubocop', '~> 1.30'
  gem 'rubocop-performance', '~> 1.14'
  gem 'rubocop-rails', '~> 2.14'
  gem 'rubocop-rspec', '~> 2.11'
  gem 'web-console', '~> 4.2'
  gem 'yard', '~> 0.9.27'
end

group :test do
  gem 'capybara', '~> 3.37'
  gem 'cuprite', '~> 0.13'
  gem 'pundit-matchers', '~> 1.7'
  gem 'rspec-snapshot', '~> 2.0'
  gem 'shoulda-matchers', '~> 5.1'
  gem 'simplecov', '~> 0.21.2'
  gem 'vcr', '~> 6.1'
  gem 'webmock', '~> 3.14'
end
