_common: &common
  adapter: postgresql
  <% if ENV['ASSET_PRECOMPILE'].present? %>
  url: nulldb://user:pass@127.0.0.1/dbname
  <% end %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>

development:
  <<: *common
  database: jove_development

test:
  <<: *common
  database: jove_test

staging:
  <<: *common
  database: jove_staging

production:
  <<: *common
  database: jove
