:dynamic: true
:schedule:
  CheckNewStaticDataVersionJob:
    cron: '0 0 * * *'
  RefreshAllESITokensJob:
    cron: '*/15 * * * *'
:queues:
  - [default, 1]
  - [low, 10]
  - [medium, 100]
  - [high, 1000]
  - [critical, 10000]
