production: &production
  url: <%= ENV.fetch("REDIS_DATA_URL", "redis://127.0.0.1:6379/0") %>
  timeout: 1

development: &development
  url: <%= ENV.fetch("REDIS_DATA_URL", "redis://127.0.0.1:6379/0") %>
  timeout: 1

test:
  url: <%= ENV.fetch("REDIS_DATA_URL", "redis://127.0.0.1:6379/8") %>
  timeout: 1
